#!/bin/bash
set -euo pipefail
# Mirror the theme's exampleSite into the demo repository.
#
# Used by the sync-theme-content and auto-sync-content workflows so both
# produce exactly the same result.
#
# Usage: bash .github/sync-theme-content.sh <theme-checkout-dir>
#
# - hugo.toml: copied, then .github/sync-config-overrides.sh is applied
# - i18n/: mirrored from exampleSite/i18n if it exists, otherwise removed.
#   Site-level i18n overrides the theme module's translations, so copying
#   the theme's root i18n/ here would only create stale shadow copies.
# - content/, static/, data/, assets/: mirrored with rsync --delete so
#   removals in the theme propagate. assets/css/critical.css is generated by
#   this repo's critical-css workflow and is left untouched.

THEME_DIR="${1:?Usage: $0 <theme-checkout-dir>}"
EXAMPLE_SITE="$THEME_DIR/exampleSite"

if [ ! -d "$EXAMPLE_SITE" ]; then
  echo "Error: '$EXAMPLE_SITE' not found."
  exit 1
fi

# hugo.toml
if [ -f "$EXAMPLE_SITE/hugo.toml" ]; then
  echo "Syncing hugo.toml..."
  cp "$EXAMPLE_SITE/hugo.toml" hugo.toml
  if [ -f ".github/sync-config-overrides.sh" ]; then
    echo "Applying demo-specific config overrides..."
    bash .github/sync-config-overrides.sh hugo.toml
  fi
else
  echo "::warning::No hugo.toml in theme exampleSite, keeping the current one"
fi

# i18n
if [ -d "$EXAMPLE_SITE/i18n" ]; then
  echo "Mirroring i18n/..."
  mkdir -p i18n
  rsync -a --delete --exclude='.git' "$EXAMPLE_SITE/i18n/" i18n/
else
  echo "No i18n/ in theme exampleSite, removing site-level i18n/ (translations come from the theme module)"
  rm -rf i18n
fi

# content, static, data, assets
for dir in content static data assets; do
  if [ ! -d "$EXAMPLE_SITE/$dir" ]; then
    echo "::warning::No $dir/ in theme exampleSite, leaving $dir/ unchanged"
    continue
  fi
  echo "Mirroring $dir/..."
  mkdir -p "$dir"
  if [ "$dir" = "assets" ]; then
    # Excluded paths are also protected from --delete
    rsync -a --delete --exclude='.git' --exclude='/css/critical.css' "$EXAMPLE_SITE/$dir/" "$dir/"
  else
    rsync -a --delete --exclude='.git' "$EXAMPLE_SITE/$dir/" "$dir/"
  fi
done

# Stage everything the sync touches, including deletions
for path in hugo.toml i18n content static data assets; do
  if [ -e "$path" ] || git ls-files --error-unmatch "$path" > /dev/null 2>&1; then
    git add -A -- "$path"
  fi
done

echo "Sync complete. Staged changes:"
git diff --cached --stat
