baseURL = "https://adritian-demo.vercel.app/"
title = "Adritian Demo"

[module]
  [[module.imports]]
    path = "github.com/zetxek/adritian-free-hugo-theme"
    branch = "172-enhancement-fix-bootstrap-import-in-the-theme"
